version: '3'

networks:
    laravel:
        driver: bridge

services:
    web:
        image: nginx:latest
        container_name: laravel_web
        networks:
            - laravel
        ports:
            - 8080:80
        volumes:
            - ./www:/app/
            - ./bin/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: ./bin
        container_name: laravel_php
        networks:
            - laravel
        volumes:
            - ./www:/app
        links:
            - database
    database:
        image: mariadb
        container_name: laravel_db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        volumes:
            - ./database-volume:/var/lib/mysql
        networks:
            - laravel
        ports:
            - 3333:3306
    mailhog:
        image: mailhog/mailhog
        container_name: laravel_mailhog
        networks:
            - laravel
        ports:
            - 8025:8025
